### ISSUE TITLE
Always not allowed

### ISSUE THREAD

**Issue by MauMaxxa** [falco442/slim-token-auth-mvc#1]
Hello man!

When i try to login i always get "Not Allowed" from here: TokenAuth.php, line 39
`if(!$token || empty($token) )
            return $response->withStatus(403)->withJSON('Not allowed');`

I already added auth inside my settings.php ...!

Thank you for your wonderful work!

**Comment by MauMaxxa** [comment]
it seems like it goes to __invoke func instead of authenticate ...?

**Comment by falco442** [comment]
Hi Mau! I'm sorry for not ginving you attention but... I was very busy! I can take a look at the issue ok?

**Comment by MauMaxxa** [comment]
Don't worry man!! :)

i solved, it was my fault!
